### PR TITLE
update Travis configuration

### PR DESCRIPTION
**Pull request by xabbuh**
- use faster container based infrastructure
- cache downloaded package archives
- report build results as soon as possible
- add dedicated job with lowest allowed dependencies
- disable the Xdebug extension to speed up builds

### CODE REVIEW

**Comment by xabbuh** [comment]
Well, that escalated quickly. :(

**Comment by jakzal** [comment]
I fixed the phpspec problem just now.

**Comment by jakzal** [comment]
There's still an issue with the DI component being to old for the framework bundle.

**Comment by jakzal** [comment]
I've sorted this out by adding symfony/framework-bundle ^2.3.24 and symfony/dom-crawler ^2.3 to dev dependencies. Otherwise the framework-bundle will fetch an old version of the DependencyInjection component, and composer will install dom-crawler 2.0 with no autoloader configuration.

**Comment by xabbuh** [comment]
@jakzal Ah, I tried it by listing all dependencies explicitly. But I'll rebase on your changes then.

**Comment by jakzal** [comment]
YAY! Thanks Christian :beers:

**Comment by xabbuh** [comment]
Thanks for the fast updates to the version constraints. :100: :beers:

**Pull request merged**
